from . import res_partner
from . import sale_order
from . import stock_rule
from . import stock_move
from . import stock_move_line
from . import stock_quant
from . import stock_picking
from . import stock_return_picking
from . import product
